version: 2.1
orbs:
  win: circleci/windows@2.2.0
  node: circleci/node@1.1.6
jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: dotnet build
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
